### ISSUE TITLE
Tomcal ssl

### ISSUE THREAD

**Issue by maskleo** [maskleo/java-faq#4]
` keytool -genkeypair -alias "tomcat" -keyalg "RSA" -keystore "z:\tomcat.keystore"`
```yml
server:
  port: 8443
  ssl:
    key-store: classpath:tomcat.keystore
    key-store-password: 123456
    key-password: 123456
    key-alias: tomcat
    enabled: true
```
